---
- hosts: elkstack
  user: vagrant
  become: yes
  roles:
    - role : nginxinc.nginx
    - role : elastic.elasticsearch
    - role : elastic.beats
    - role : geerlingguy.kibana
  vars:
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    se_users:
      native:
        kibana4_server:
          password: +QAY2wsx3edc
          roles:
            - kibana4_server
      file:
        es_admin:
          password: +QAY2wsx3edc
          roles:
            - admin
        testUser:
          password: +QAY2wsx3edc
          roles:
            - power_user
            - user
    beats_version: 7.0.0
    beat: filebeat
    beat_conf:
      inputs:
        - type: log
          enabled: true
          paths:
            - /var/log/*.log
